// import "./globals.css";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

import { UserButton } from "@clerk/nextjs";

export const metadata = {
  title: "CineQueue",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className=" absolute top-0 right-0 w-full h-[10%] flex justify-center items-center">
        <div className=" w-5/6 h-full flex justify-end items-center">
          <UserButton afterSignOutUrl="/" />
        </div>
      </div>
      <div className=" w-screen h-screen">{children}</div>
    </>
  );
}
